# -*- coding: utf-8 -*-
"""PII Data Retraction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17za8PrtuY2UZeAGxUPr-Tta61x-KGVZ6
"""

# Install Tesseract (OCR) and LibreOffice (Document Conversion)
# !sudo apt-get update && sudo apt-get install -y tesseract-ocr tesseract-ocr-eng libreoffice

# # Install Python dependencies
# !pip install pymupdf presidio-analyzer spacy google-api-python-client google-auth-httplib2 google-auth-oauthlib
# !pip install spacy-transformers openpyxl python-docx python-pptx pytesseract Pillow
# !python -m spacy download en_core_web_trf

import logging
import warnings
import pymupdf
import os
import io
import json
import subprocess
import openpyxl
import docx
import time
import re
import csv
import spacy
import threading
import pptx
import pytesseract
from PIL import Image, ImageDraw

logging.getLogger("presidio-analyzer").setLevel(logging.ERROR)
warnings.filterwarnings("ignore", message=".*toDlpack.*")
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=UserWarning)

try:
    spacy.require_gpu()
    print("GPU Acceleration Enabled for NLP Engines.")
except Exception as e:
    print("No GPU detected. Falling back to CPU.")

from presidio_analyzer import AnalyzerEngine, Pattern, PatternRecognizer, RecognizerRegistry
from presidio_analyzer.nlp_engine import NlpEngineProvider
from google.colab import userdata
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload, MediaFileUpload

INPUT_FOLDER_ID = '1Hm1ayHR4PcRHbfiFrQr3Y3LkCWmUnYlI'
OUTPUT_FOLDER_ID = '1iLuUZUSF6BjhIF2WzMB39_-K-ahDQnKj'

ENTITIES_STANDARD = ["PERSON", "EMAIL_ADDRESS", "PHONE_NUMBER", "CREDIT_CARD", "US_SSN", "LOCATION", "STREET_ADDRESS"]
ENTITIES_TRANSFORMER = ["ORGANIZATION","DYNAMIC_COMPANY_NAME"]

SAFE_LIST = {
    "u.s.", "u.s", "us", "usa", "united states", "united kingdom", "u.k.", "uk",
    "the company", "our company", "this company", "company",
    "the group", "our group", "this group", "group",
    "the bank", "our bank", "this bank", "bank"
}

TEXT_CACHE = {}
AUDIT_LOG = {}
GPU_LOCK = threading.Lock()

service_account_info = json.loads(userdata.get('SERVICE_ACCOUNT_JSON'))
SCOPES = ['https://www.googleapis.com/auth/drive']
creds = service_account.Credentials.from_service_account_info(service_account_info, scopes=SCOPES)

provider_std = NlpEngineProvider(nlp_configuration={"nlp_engine_name": "spacy", "models": [{"lang_code": "en", "model_name": "en_core_web_lg"}]})
engine_std = provider_std.create_engine()
registry_std = RecognizerRegistry()
registry_std.load_predefined_recognizers(nlp_engine=engine_std)

phone_patterns = [
    Pattern(name="us_phone", regex=r"\b(?:\+?1[-.\s]?)?\(?[2-9]\d{2}\)?[-.\s]?[2-9]\d{2}[-.\s]?\d{4}\b", score=0.9),
    Pattern(name="intl_phone", regex=r"\b\+\d{1,3}[-.\s]?\(?\d{1,4}\)?[-.\s]?\d{1,4}[-.\s]?\d{1,4}\b", score=0.9),
    Pattern(name="phone_with_ext", regex=r"\b\(?[2-9]\d{2}\)?[-.\s]?[2-9]\d{2}[-.\s]?\d{4}[-.\s]?(?:ext|x)\.?\s?\d{1,5}\b", score=0.9)
]
registry_std.add_recognizer(PatternRecognizer(supported_entity="PHONE_NUMBER", patterns=phone_patterns))
address_regex = r"\b\d{1,5}\s(?:[A-Za-z0-9#.-]+\s){1,5}(?:St|Street|Ave|Avenue|Rd|Road|Blvd|Boulevard|Ln|Lane|Dr|Drive|Ct|Court|Cir|Circle|Way|Trl|Trail|Pkwy|Parkway|Sq|Square|Bldg|Building|Suite|Ste|Apt|Apartment)\b"
registry_std.add_recognizer(PatternRecognizer(supported_entity="STREET_ADDRESS", patterns=[Pattern(name="street_address", regex=address_regex, score=0.8)]))
analyzer_standard = AnalyzerEngine(nlp_engine=engine_std, registry=registry_std)

provider_trf = NlpEngineProvider(nlp_configuration={"nlp_engine_name": "spacy", "models": [{"lang_code": "en", "model_name": "en_core_web_trf"}]})
engine_trf = provider_trf.create_engine()
registry_trf = RecognizerRegistry()
registry_trf.load_predefined_recognizers(nlp_engine=engine_trf)

for rec in registry_trf.recognizers:
    if rec.name == "SpacyRecognizer" and "ORGANIZATION" not in rec.supported_entities:
        rec.supported_entities.append("ORGANIZATION")

corporate_regex = r"\b(?:(?!(?:The|A|An|Our|Their|Your|This|That|Any)\b)[A-Z][a-zA-Z0-9&',-]*\s+){1,4}(?:LLC|L\.L\.C\.|Inc\.?|Corp\.?|Corporation|Ltd\.?|Company|Co\.?|Group|Plc|llc|inc|corp|ltd|company|co\.?|group|plc)\b"
registry_trf.add_recognizer(PatternRecognizer(supported_entity="DYNAMIC_COMPANY_NAME", patterns=[Pattern(name="corporate_suffix", regex=corporate_regex, score=0.9)]))
analyzer_transformer = AnalyzerEngine(nlp_engine=engine_trf, registry=registry_trf)

def replace_with_blocks(text, file_name):
    if not isinstance(text, str) or not text.strip(): return text, 0
    if text in TEXT_CACHE: return TEXT_CACHE[text]

    with GPU_LOCK:
        res_std = analyzer_standard.analyze(text=text, entities=ENTITIES_STANDARD, language='en', score_threshold=0.8)
        res_trf = analyzer_transformer.analyze(text=text, entities=ENTITIES_TRANSFORMER, language='en', score_threshold=0.8)

    combined_results = res_std + res_trf
    if not combined_results:
        TEXT_CACHE[text] = (text, 0)
        return text, 0

    combined_results.sort(key=lambda x: x.start, reverse=True)
    new_text = text
    count = 0
    for res in combined_results:
        match_str = text[res.start:res.end].strip()
        if match_str.lower() not in SAFE_LIST and len(match_str) > 3:
            if file_name not in AUDIT_LOG: AUDIT_LOG[file_name] = set()
            AUDIT_LOG[file_name].add(match_str)
            length = res.end - res.start
            new_text = new_text[:res.start] + ("█" * length) + new_text[res.end:]
            count += 1

    TEXT_CACHE[text] = (new_text, count)
    return new_text, count

def redact_pdf(input_path, output_path, file_name):
    doc = pymupdf.open(input_path)
    total_yield = 0

    for page in doc:
        page_height, page_width = page.rect.height, page.rect.width
        text = page.get_text()
        textpage = None
        if len(text.strip()) < 50:
            try:
                textpage = page.get_textpage_ocr(flags=0, language='eng', dpi=150)
                text = page.get_text(textpage=textpage)
            except Exception: pass

        for img in page.get_image_info():
            if img.get("bbox") and pymupdf.Rect(img["bbox"]).y0 < (page_height * 0.08) and pymupdf.Rect(img["bbox"]).width < (page_width * 0.5):
                page.add_redact_annot(pymupdf.Rect(img["bbox"]), fill=(0, 0, 0))
                total_yield += 1

        for drawing in page.get_drawings():
            draw_rect = drawing.get("rect")
            if draw_rect and draw_rect.y0 < (page_height * 0.08) and draw_rect.width < (page_width * 0.5) and draw_rect.height < (page_height * 0.3):
                page.add_redact_annot(draw_rect, fill=(0, 0, 0))
                total_yield += 1

        corp_keywords = ['LLC', 'L.L.C', 'Inc', 'Corp', 'Corporation', 'Ltd', 'Company', 'Co.', 'Group', 'Plc', 'Bank']
        blocks = page.get_text("blocks", textpage=textpage) if textpage else page.get_text("blocks")
        for block in blocks:
            x0, y0, x1, y1, block_text, block_no, block_type = block
            if y0 < (page_height * 0.08) and block_type == 0 and pymupdf.Rect(x0, y0, x1, y1).width < (page_width * 0.5):
                if any(k.lower() in block_text.lower() for k in corp_keywords):
                    page.add_redact_annot(pymupdf.Rect(x0, y0, x1, y1), fill=(0, 0, 0))
                    total_yield += 1

        if text.strip():
            clean_text = text.replace('\n', ' ')
            with GPU_LOCK:
                res_std = analyzer_standard.analyze(text=clean_text, entities=ENTITIES_STANDARD, language='en', score_threshold=0.8)
                res_trf = analyzer_transformer.analyze(text=clean_text, entities=ENTITIES_TRANSFORMER, language='en', score_threshold=0.8)

            raw_pii = set([clean_text[res.start:res.end].strip() for res in (res_std + res_trf) if len(clean_text[res.start:res.end].strip()) > 3])
            for match in re.finditer(corporate_regex, clean_text):
                raw_pii.add(match.group().strip())

            pii_strings = {p for p in raw_pii if p.lower() not in SAFE_LIST}

            for pii in pii_strings:
                if not pii: continue
                if file_name not in AUDIT_LOG: AUDIT_LOG[file_name] = set()
                AUDIT_LOG[file_name].add(pii)

                if textpage:
                    ocr_words = page.get_text("words", textpage=textpage)
                    pii_parts = [w.lower() for w in pii.split()]
                    for w in ocr_words:
                        clean_w = "".join(c for c in w[4].lower() if c.isalnum())
                        if clean_w in pii_parts and len(clean_w) > 2:
                            page.add_redact_annot(pymupdf.Rect(w[:4]), fill=(0, 0, 0))
                            total_yield += 1
                else:
                    areas = page.search_for(pii)
                    if areas:
                        for area in areas:
                            page.add_redact_annot(area, fill=(0, 0, 0))
                            total_yield += 1
                    else:
                        for word in pii.split():
                            clean_w = "".join(c for c in word.lower() if c.isalnum())
                            if len(clean_w) > 2 and not clean_w.isdigit():
                                for w_area in page.search_for(word.strip()):
                                    page.add_redact_annot(w_area, fill=(0, 0, 0))
                                    total_yield += 1

        page.apply_redactions(images=pymupdf.PDF_REDACT_IMAGE_PIXELS, graphics=True)

    doc.save(output_path, garbage=4, deflate=True)
    doc.close()
    return total_yield

def redact_excel(input_path, output_path, file_name):
    wb = openpyxl.load_workbook(input_path)
    total_yield = 0
    for sheet_name in wb.sheetnames:
        for row in wb[sheet_name].iter_rows():
            for cell in row:
                if cell.value and isinstance(cell.value, str):
                    new_val, count = replace_with_blocks(cell.value, file_name)
                    cell.value = new_val
                    total_yield += count
    wb.save(output_path)
    return total_yield

def redact_word(input_path, output_path, file_name):
    doc = docx.Document(input_path)
    total_yield = 0
    for para in doc.paragraphs:
        if para.text:
            new_val, count = replace_with_blocks(para.text, file_name)
            para.text = new_val
            total_yield += count
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                if cell.text:
                    new_val, count = replace_with_blocks(cell.text, file_name)
                    cell.text = new_val
                    total_yield += count
    for section in doc.sections:
        for header_para in section.header.paragraphs:
            if header_para.text:
                new_val, count = replace_with_blocks(header_para.text, file_name)
                header_para.text = new_val
                total_yield += count
        for footer_para in section.footer.paragraphs:
            if footer_para.text:
                new_val, count = replace_with_blocks(footer_para.text, file_name)
                footer_para.text = new_val
                total_yield += count
    doc.save(output_path)
    return total_yield

def redact_pptx(input_path, output_path, file_name):
    prs = pptx.Presentation(input_path)
    total_yield = 0
    for slide in prs.slides:
        for shape in slide.shapes:
            if hasattr(shape, "text") and shape.text:
                new_val, count = replace_with_blocks(shape.text, file_name)
                shape.text = new_val
                total_yield += count
    prs.save(output_path)
    return total_yield

def redact_image_native(input_path, output_path, file_name, ext):
    image = Image.open(input_path)
    if image.mode not in ("RGB", "RGBA"): image = image.convert("RGBA")

    # OCR the image to get raw text for AI analysis
    raw_text = pytesseract.image_to_string(image)
    if len(raw_text.strip()) < 3:
        image.save(output_path)
        return 0

    # Feed text to AI engines
    clean_text = raw_text.replace('\n', ' ')
    with GPU_LOCK:
        res_std = analyzer_standard.analyze(text=clean_text, entities=ENTITIES_STANDARD, language='en', score_threshold=0.8)
        res_trf = analyzer_transformer.analyze(text=clean_text, entities=ENTITIES_TRANSFORMER, language='en', score_threshold=0.8)

    raw_pii = set([clean_text[res.start:res.end].strip() for res in (res_std + res_trf) if len(clean_text[res.start:res.end].strip()) > 3])
    for match in re.finditer(corporate_regex, clean_text):
        raw_pii.add(match.group().strip())

    pii_strings = {p for p in raw_pii if p.lower() not in SAFE_LIST}

    if not pii_strings:
        image.save(output_path)
        return 0

    # Find the visual coordinates of the PII and paint black boxes
    total_yield = 0
    data = pytesseract.image_to_data(image, output_type=pytesseract.Output.DICT)
    draw = ImageDraw.Draw(image)

    for pii in pii_strings:
        if file_name not in AUDIT_LOG: AUDIT_LOG[file_name] = set()
        AUDIT_LOG[file_name].add(pii)

        pii_parts = [w.lower() for w in pii.split()]
        for i in range(len(data['text'])):
            word = data['text'][i].strip()
            clean_w = "".join(c for c in word.lower() if c.isalnum())
            if len(clean_w) > 2 and clean_w in pii_parts:
                x, y, w, h = data['left'][i], data['top'][i], data['width'][i], data['height'][i]
                draw.rectangle([x, y, x + w, y + h], fill="black")
                total_yield += 1

    image.save(output_path)
    return total_yield

from concurrent.futures import ThreadPoolExecutor, as_completed
import csv
import os
import gc
import threading
import subprocess
import time
import zipfile
import shutil
from PIL import Image

LOCAL_IN = '/content/temp_in'
LOCAL_OUT = '/content/temp_out'
LOCAL_ZIP_DIR = '/content/temp_zips'
LOCAL_UNZIP_DIR = '/content/temp_unzipped'
os.makedirs(LOCAL_IN, exist_ok=True)
os.makedirs(LOCAL_OUT, exist_ok=True)
os.makedirs(LOCAL_ZIP_DIR, exist_ok=True)
os.makedirs(LOCAL_UNZIP_DIR, exist_ok=True)

master_drive_service = build('drive', 'v3', credentials=creds)
AUDIT_LOCK = threading.Lock()

# ------------------------------------------------------------------
# ZIP PRE-PROCESSING (Extracts to Drive before main pipeline runs)
# ------------------------------------------------------------------
def create_drive_folder(name, parent_id):
    metadata = {'name': name, 'mimeType': 'application/vnd.google-apps.folder', 'parents': [parent_id]}
    folder = master_drive_service.files().create(body=metadata, fields='id', supportsAllDrives=True).execute()
    return folder.get('id')

def upload_extracted_contents(local_dir, parent_drive_id):
    for item in os.listdir(local_dir):
        item_path = os.path.join(local_dir, item)
        if os.path.isdir(item_path):
            new_folder_id = create_drive_folder(item, parent_drive_id)
            upload_extracted_contents(item_path, new_folder_id)
        else:
            media = MediaFileUpload(item_path, resumable=True)
            master_drive_service.files().create(
                body={'name': item, 'parents': [parent_drive_id]},
                media_body=media, fields='id', supportsAllDrives=True
            ).execute()

print("Scanning for .zip archives...")
query = f"'{INPUT_FOLDER_ID}' in parents and mimeType='application/zip' and trashed=false"
results = master_drive_service.files().list(q=query, fields="files(id, name)", supportsAllDrives=True).execute()
zip_files = results.get('files', [])

if not zip_files:
    print("No .zip files found to extract. Proceeding to main pipeline...\n")
else:
    for index, z_file in enumerate(zip_files, start=1):
        z_id, z_name = z_file['id'], z_file['name']
        print(f"[{index}/{len(zip_files)}] Extracting ZIP: {z_name}")

        local_zip_path = os.path.join(LOCAL_ZIP_DIR, z_name)
        extract_path = os.path.join(LOCAL_UNZIP_DIR, z_name.replace('.zip', ''))
        os.makedirs(extract_path, exist_ok=True)

        # 1. Download
        request = master_drive_service.files().get_media(fileId=z_id, acknowledgeAbuse=True)
        with open(local_zip_path, 'wb') as fh:
            downloader = MediaIoBaseDownload(fh, request)
            done = False
            while not done: _, done = downloader.next_chunk()

        # 2. Extract
        with zipfile.ZipFile(local_zip_path, 'r') as zip_ref:
            zip_ref.extractall(extract_path)

        # 3. Upload unzipped contents back to the Input Folder
        print(f"   ↳ Uploading extracted contents to Drive...")
        upload_extracted_contents(extract_path, INPUT_FOLDER_ID)

        # 4. Cleanup local storage and trash original ZIP so it isn't repeated
        os.remove(local_zip_path)
        shutil.rmtree(extract_path)
        master_drive_service.files().update(fileId=z_id, body={'trashed': True}).execute()
        print(f"   ↳ Moved original {z_name} to Drive Trash.")

    print("\n=== ZIP Pre-processing Complete ===\n")

# ------------------------------------------------------------------
# GLOBAL CACHES
# ------------------------------------------------------------------
if 'FOLDER_MAP' not in globals(): FOLDER_MAP = {}
NESTED_CHECKPOINTS = {}

def get_or_create_folder(folder_name, parent_id):
    safe_folder_name = folder_name.replace("'", "\\'")
    query = f"'{parent_id}' in parents and name='{safe_folder_name}' and mimeType='application/vnd.google-apps.folder' and trashed=false"
    results = master_drive_service.files().list(q=query, fields="files(id)", supportsAllDrives=True, includeItemsFromAllDrives=True).execute()
    files = results.get('files', [])
    if files: return files[0]['id']

    folder_metadata = {'name': folder_name, 'mimeType': 'application/vnd.google-apps.folder', 'parents': [parent_id]}
    folder = master_drive_service.files().create(body=folder_metadata, fields='id', supportsAllDrives=True).execute()
    return folder.get('id')

def mirror_structure_and_get_files(source_folder_id, dest_folder_id):
    files_to_process = []

    # Paginated Checkpoint Crawling
    existing_names = set()
    page_token = None
    while True:
        existing_query = f"'{dest_folder_id}' in parents and trashed=false"
        existing_results = master_drive_service.files().list(q=existing_query, fields="nextPageToken, files(name)", pageSize=1000, pageToken=page_token, supportsAllDrives=True, includeItemsFromAllDrives=True).execute()
        for f in existing_results.get('files', []): existing_names.add(f['name'])
        page_token = existing_results.get('nextPageToken')
        if not page_token: break
    NESTED_CHECKPOINTS[dest_folder_id] = existing_names

    # Paginated Input Crawling
    page_token = None
    while True:
        query = f"'{source_folder_id}' in parents and trashed=false"
        results = master_drive_service.files().list(q=query, fields="nextPageToken, files(id, name, mimeType)", pageSize=1000, pageToken=page_token, supportsAllDrives=True, includeItemsFromAllDrives=True).execute()
        items = results.get('files', [])

        for item in items:
            if item['mimeType'] == 'application/vnd.google-apps.folder':
                input_sub_id = item['id']
                if input_sub_id not in FOLDER_MAP:
                    print(f"Mapping directory: {item['name']} ...")
                    FOLDER_MAP[input_sub_id] = get_or_create_folder(item['name'], dest_folder_id)
                files_to_process.extend(mirror_structure_and_get_files(input_sub_id, FOLDER_MAP[input_sub_id]))
            else:
                files_to_process.append({'id': item['id'], 'name': item['name'], 'dest_folder_id': dest_folder_id})

        page_token = results.get('nextPageToken')
        if not page_token: break
    return files_to_process

# ------------------------------------------------------------------
# THREAD WORKERS
# ------------------------------------------------------------------
def download_and_convert_worker(file, dest_folder_id, creds):
    try:
        file_id, file_name = file['id'], file['name']
        original_ext = os.path.splitext(file_name)[1].lower()
        local_in_path = os.path.join(LOCAL_IN, file_name)

        thread_drive = build('drive', 'v3', credentials=creds)
        request = thread_drive.files().get_media(fileId=file_id, acknowledgeAbuse=True)
        with open(local_in_path, 'wb') as fh:
            downloader = MediaIoBaseDownload(fh, request)
            done = False
            while not done: _, done = downloader.next_chunk()

        target_ext, target_path = original_ext, local_in_path

        # Isolate legacy docs and web archives for LibreOffice conversion
        if original_ext == '.doc':
            target_ext = '.docx'
            subprocess.run(['libreoffice', '--headless', '--convert-to', 'docx', local_in_path, '--outdir', LOCAL_IN], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            file_name = f"{os.path.splitext(file_name)[0]}{target_ext}"
            target_path = os.path.join(LOCAL_IN, file_name)
        elif original_ext == '.xls':
            target_ext = '.xlsx'
            subprocess.run(['libreoffice', '--headless', '--convert-to', 'xlsx', local_in_path, '--outdir', LOCAL_IN], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            file_name = f"{os.path.splitext(file_name)[0]}{target_ext}"
            target_path = os.path.join(LOCAL_IN, file_name)
        elif original_ext in ['.mht', '.mhtml']:
            target_ext = '.pdf'
            subprocess.run(['libreoffice', '--headless', '--convert-to', 'pdf', local_in_path, '--outdir', LOCAL_IN], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            file_name = f"{os.path.splitext(file_name)[0]}{target_ext}"
            target_path = os.path.join(LOCAL_IN, file_name)

        # Native formats (.pptx, .jpg, .png, etc.) bypass conversion here

        return True, target_path, target_ext, file_name, dest_folder_id, local_in_path, file['name'], original_ext
    except Exception as e:
        return False, None, None, None, None, None, f"{file['name']} | Download Error: {e}", None

def background_upload(local_out_path, file_name, dest_folder_id, creds):
    try:
        thread_drive = build('drive', 'v3', credentials=creds)
        media = MediaFileUpload(local_out_path, mimetype='application/octet-stream', resumable=True)
        thread_drive.files().create(body={'name': f"REDACTED_{file_name}", 'parents': [dest_folder_id]}, media_body=media, fields='id', supportsAllDrives=True).execute()
        if os.path.exists(local_out_path): os.remove(local_out_path)
    except Exception as e:
        print(f"   ↳ Upload Failed for {file_name} | Error: {e}")

# ------------------------------------------------------------------
# MAIN EXECUTION (PRODUCER-CONSUMER)
# ------------------------------------------------------------------
print("Scanning Master Folder and establishing structure...")
files = mirror_structure_and_get_files(INPUT_FOLDER_ID, OUTPUT_FOLDER_ID)

if files:
    print(f"\nFound {len(files)} file(s). Starting Continuous DGX Pipeline...\n")
    pipeline_start = time.time()
    total_pipeline_yield = 0
    completed_files = 0

    audit_filename = "Redaction_Audit_Log.csv"
    audit_local_path = os.path.join(LOCAL_OUT, audit_filename)
    query = f"'{OUTPUT_FOLDER_ID}' in parents and name='{audit_filename}' and trashed=false"
    results = master_drive_service.files().list(q=query, fields="files(id)", supportsAllDrives=True, includeItemsFromAllDrives=True).execute()

    if results.get('files', []):
        audit_file_id = results.get('files')[0]['id']
        request = master_drive_service.files().get_media(fileId=audit_file_id)
        with open(audit_local_path, 'wb') as fh:
            downloader = MediaIoBaseDownload(fh, request)
            done = False
            while not done: _, done = downloader.next_chunk()
    else:
        with open(audit_local_path, 'w', newline='', encoding='utf-8') as f:
            csv.writer(f).writerow(["Source File", "Processing Time (s)", "Total Redactions", "Redacted Terms"])
        audit_file = master_drive_service.files().create(body={'name': audit_filename, 'parents': [OUTPUT_FOLDER_ID]}, media_body=MediaFileUpload(audit_local_path, mimetype='text/csv'), fields='id', supportsAllDrives=True).execute()
        audit_file_id = audit_file.get('id')

    download_executor = ThreadPoolExecutor(max_workers=3)
    upload_executor = ThreadPoolExecutor(max_workers=3)

    # Pre-load files into the background downloader
    active_downloads = {}
    for file in files:
        if f"REDACTED_{file['name']}" in NESTED_CHECKPOINTS.get(file['dest_folder_id'], set()):
            print(f"   ↳ Skipped: {file['name']} (Already processed)")
            completed_files += 1
            continue
        future = download_executor.submit(download_and_convert_worker, file, file['dest_folder_id'], creds)
        active_downloads[future] = file['name']

    # GPU processes files safely on main thread
    for future in as_completed(active_downloads):
        completed_files += 1
        success, target_path, target_ext, file_name, dest_folder_id, local_in_path, original_name, original_ext = future.result()

        print(f"[{completed_files}/{len(files)}] Processing: {original_name}")

        if not success:
            print(f"   ↳ Failed: {original_name}")
            continue

        try:
            local_out_path = os.path.join(LOCAL_OUT, f"REDACTED_{file_name}")
            file_start = time.time()
            file_yield = 0

            # --- DYNAMIC ROUTING ---
            if target_ext == '.pdf': file_yield = redact_pdf(target_path, local_out_path, file_name)
            elif target_ext == '.xlsx': file_yield = redact_excel(target_path, local_out_path, file_name)
            elif target_ext == '.docx': file_yield = redact_word(target_path, local_out_path, file_name)
            elif target_ext == '.pptx': file_yield = redact_pptx(target_path, local_out_path, file_name)
            elif target_ext in ['.jpg', '.jpeg', '.png', '.gif']:
                file_yield = redact_image_native(target_path, local_out_path, file_name, target_ext)
            elif original_ext in ['.mp4', '.mp3', '.flv', '.swf']:
                print(f"   ↳ Skipped: {original_name} (Unsupported Media/Audio)")
                if os.path.exists(local_in_path): os.remove(local_in_path)
                continue
            elif original_ext == '.zip':
                print(f"   ↳ Skipped: {original_name} (Archived file; already processed in pre-processing)")
                if os.path.exists(local_in_path): os.remove(local_in_path)
                continue
            else:
                print(f"   ↳ Skipped: {original_name} (Unsupported format)")
                if os.path.exists(local_in_path): os.remove(local_in_path)
                continue

            file_time = time.time() - file_start
            total_pipeline_yield += file_yield
            print(f"   ↳ Success: Redacted {file_yield} items in {file_time:.2f}s.")

            # Audit Logging
            with AUDIT_LOCK:
                terms_found = AUDIT_LOG.pop(file_name, set())
                terms_str = ", ".join(sorted(terms_found)) if terms_found else "None"
                with open(audit_local_path, 'a', newline='', encoding='utf-8') as f:
                    csv.writer(f).writerow([file_name, f"{file_time:.2f}", file_yield, terms_str])
                master_drive_service.files().update(fileId=audit_file_id, media_body=MediaFileUpload(audit_local_path, mimetype='text/csv', resumable=True), supportsAllDrives=True).execute()

            # Send to background uploader
            upload_executor.submit(background_upload, local_out_path, file_name, dest_folder_id, creds)

            if os.path.exists(local_in_path): os.remove(local_in_path)
            if target_path != local_in_path and os.path.exists(target_path): os.remove(target_path)
            if len(TEXT_CACHE) > 20000: TEXT_CACHE.clear()

        except Exception as e:
            print(f"   ↳ Failed: {original_name} | Error: {e}")

        gc.collect()

    print("\nWaiting for final files to upload to Drive...")
    upload_executor.shutdown(wait=True)
    download_executor.shutdown(wait=True)

    print("\n=== Redaction Job Complete ===")
    print(f"Total Throughput Time: {time.time() - pipeline_start:.2f} seconds")
    print(f"Total Redaction Yield: {total_pipeline_yield} items")